# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'urcal_rn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for urcal_rn
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'

  target 'urcal_rn-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'urcal_rnTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'urcal_rn-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for urcal_rn-tvOS


end
